name: Test Container Build

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  docker_test:
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    name: Test the Docker Container Build
    defaults:
      run:
        shell: bash --noprofile --norc -eo pipefail -x {0}

    env:
      DOCKER_BUILDKIT: "1"

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run docker build
        run: |
          docker build . -t node-playwright-base-image